### PR TITLE
Features

### PR DESCRIPTION
**Pull request by Reycko**
- Friends
- Hide watermark (can remove if not wanted)
- Toggle for autokill to allow killing in lobbies (it causes the lobby to die on game start)
- Make the game settings tab on the host way easier to read on the code (-200 lines, replaces if-else spam with a lambda)

### CODE REVIEW

**Comment by Reycko** [comment]
Friends are still wip, for now friends dont get caught by GetAllPlayerControl() unless explicitly stated in the function call

**Comment by terrifyiedz** [comment]
Sicko menu  is streamble with some softwares.

AutoKill, that's just how you get banned easily and get listed on the among cheaters list

**Comment by Reycko** [comment]
> Sicko menu is streamble with some softwares.

The d3dpresent hook has been removed at some point so i don't really see what you mean by this

> AutoKill, that's just how you get banned easily and get listed on the among cheaters list
I didn't change autokill other than avoiding killing inside of lobbies, so i dont see why you bring it up

**Comment by terrifyiedz** [comment]
Generally removed using kill options in the lobby mainly because it would the game and the server the same when you are to the host tab.

**Comment by Reycko** [comment]
> Generally removed using kill options in the lobby mainly because it would the game and the server the same when you are to the host tab.

uhh what

**Comment by g0aty** [comment]
These changes are solid, I'll update the menu to v3.6!

**Pull request merged**
